name 'gocd-agent-linux'
maintainer 'Steven Wade'
maintainer_email 'wades@parliament.uk'
license 'all_rights'
description 'Installs/Configures a Go.cd linux agent'
long_description 'Installs/Configures a Go.cd linux agent'
version '0.1.1'
depends 'gocd'
depends 'chef-dk'
depends 'git'
